### ISSUE TITLE
テストの記述

### ISSUE THREAD

**Issue by neila** [unchain-tech/NEAR-MulPay#3]
- [x] **網羅的な**テストスクリプトを追加する (unit test, integration test, チェックエラー, etc)
- [x] https://github.com/shiftbase-inc/UNCHAIN-test-submissions から実行できるようにする

**Comment by honganji** [comment]
テストスクリプトの追加と、[自動テスト](https://github.com/shiftbase-inc/UNCHAIN-test-submissions)からの実行ができるようにしました。
